version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env # you can also define env variables like this.
  rails:
    build: ./ 
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container

volumes:
  postgres: # named volume